# Generated by Django 2.2.2 on 2019-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190706_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('aadhar_number', models.TextField()),
                ('No_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
            ],
        ),
    ]
